# Generated by Django 4.0.5 on 2022-06-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50)),
                ('prioridade', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=8)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
